apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: todo-app
  labels:
    app: todo-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-label
  template:
    metadata:
      name: todo-pod
      labels:
        app: todo-label
    spec:
      containers:
      - name: todo-ctr
        image: sumit9730/node-app
        ports:
          - containerPort: 8000

